/**
 * Oracle DOT-parity helpers.
 *
 * Parses the Svek DOT the oracle dumps (`svek-*.dot`) and plantuml-ts's own
 * layout input (`DotInputGraph`) into a common id-agnostic structural model,
 * then compares them. This is the structural half of the staged gate
 * (oracle/README.md): node/edge topology and `minlen` must match exactly;
 * `width`/`height` are tolerant metrics (they bake in Java vs plantuml-ts text
 * measurement) and are reported, not asserted.
 *
 * The Svek DOT is generated by graphviz's own emitter, so it is regular enough
 * to parse with focused regexes rather than a full DOT grammar: nodes are
 * `<id> [shape=rect,...,width=<in>,height=<in>,...]`, edges are
 * `<a>-><b>[...,minlen=<n>,...]`, both terminated by `]` with no nested `]`.
 */
import type { DotInputGraph } from '../../src/core/graph-layout.js';

export interface StructuralNode {
  id: string;
  /** inches (the unit both sides are normalized to) */
  width: number;
  height: number;
}
export interface StructuralEdge {
  from: string;
  to: string;
  minlen: number;
}
export interface StructuralGraph {
  nodes: StructuralNode[];
  edges: StructuralEdge[];
  nodesep: number | undefined;
  ranksep: number | undefined;
  /** Raw `subgraph cluster…` count — informational; Svek wraps each cluster in
   *  padding subgraphs, so this is not a clean cluster count. */
  subgraphCount: number;
}

const PX_PER_INCH = 72;

const attr = (attrs: string, name: string): string | undefined =>
  new RegExp(`\\b${name}=([0-9.]+)`).exec(attrs)?.[1];

/** Parse the oracle's Svek DOT into the structural model. */
export function parseSvekDot(dot: string): StructuralGraph {
  const edges: StructuralEdge[] = [];
  const edgeRe = /(\w+)\s*->\s*(\w+)\s*\[([^\]]*)\]/g;
  for (let m = edgeRe.exec(dot); m !== null; m = edgeRe.exec(dot)) {
    edges.push({
      from: m[1]!,
      to: m[2]!,
      minlen: Number(attr(m[3]!, 'minlen') ?? '1'),
    });
  }

  // Node decls — exclude the edge spans so an edge's `[...]` is never reparsed.
  const withoutEdges = dot.replace(edgeRe, '');
  const nodes: StructuralNode[] = [];
  const nodeRe = /(\w+)\s*\[([^\]]*)\]/g;
  for (let m = nodeRe.exec(withoutEdges); m !== null; m = nodeRe.exec(withoutEdges)) {
    const attrs = m[2]!;
    if (!/shape=rect/.test(attrs)) continue; // skip cluster-label TABLEs etc.
    nodes.push({
      id: m[1]!,
      width: Number(attr(attrs, 'width') ?? '0'),
      height: Number(attr(attrs, 'height') ?? '0'),
    });
  }

  return {
    nodes,
    edges,
    nodesep: numAttr(dot, 'nodesep'),
    ranksep: numAttr(dot, 'ranksep'),
    subgraphCount: (dot.match(/subgraph\s+cluster/g) ?? []).length,
  };
}

function numAttr(dot: string, name: string): number | undefined {
  const v = new RegExp(`(?:^|\\n|\\s)${name}=([0-9.]+);`).exec(dot)?.[1];
  return v === undefined ? undefined : Number(v);
}

/** Project plantuml-ts's layout input into the same model (px → inches). */
export function dotInputToStructural(input: DotInputGraph): StructuralGraph {
  return {
    nodes: input.nodes.map((n) => ({
      id: n.id,
      width: n.width / PX_PER_INCH,
      height: n.height / PX_PER_INCH,
    })),
    edges: input.edges.map((e) => ({
      from: e.from,
      to: e.to,
      minlen: e.attributes?.minLen ?? 1,
    })),
    nodesep: input.nodeSep === undefined ? undefined : input.nodeSep / PX_PER_INCH,
    ranksep: input.rankSep === undefined ? undefined : input.rankSep / PX_PER_INCH,
    subgraphCount: 0,
  };
}

/** Sorted undirected degree multiset — an id-agnostic topology signature. */
export function degreeSequence(g: StructuralGraph): number[] {
  const deg = new Map<string, number>();
  for (const n of g.nodes) deg.set(n.id, 0);
  for (const e of g.edges) {
    deg.set(e.from, (deg.get(e.from) ?? 0) + 1);
    deg.set(e.to, (deg.get(e.to) ?? 0) + 1);
  }
  return [...deg.values()].sort((a, b) => a - b);
}

const eqSeq = (a: number[], b: number[]): boolean =>
  a.length === b.length && a.every((v, i) => v === b[i]);

export interface StructuralDiff {
  nodeCountOk: boolean;
  edgeCountOk: boolean;
  degreeOk: boolean;
  minlenOk: boolean;
  /** True when all of the above hold — the fail-fast structural gate. */
  structurallyEqual: boolean;
  oracle: { nodes: number; edges: number; degree: number[]; subgraphs: number };
  candidate: { nodes: number; edges: number; degree: number[] };
  /** Tolerant metric note: largest single node-dimension delta (inches). */
  maxSizeDeltaIn: number;
  attrs: {
    oracle: [number | undefined, number | undefined];
    candidate: [number | undefined, number | undefined];
  };
}

export function compareStructural(
  oracle: StructuralGraph,
  candidate: StructuralGraph,
): StructuralDiff {
  const od = degreeSequence(oracle);
  const cd = degreeSequence(candidate);
  const minlens = (g: StructuralGraph): number[] =>
    g.edges.map((e) => e.minlen).sort((a, b) => a - b);

  const nodeCountOk = oracle.nodes.length === candidate.nodes.length;
  const edgeCountOk = oracle.edges.length === candidate.edges.length;
  const degreeOk = eqSeq(od, cd);
  const minlenOk = eqSeq(minlens(oracle), minlens(candidate));

  // Tolerant metric: compare sorted node-size multisets (no id correspondence).
  const sizes = (g: StructuralGraph): number[] =>
    [...g.nodes.map((n) => n.width), ...g.nodes.map((n) => n.height)].sort((a, b) => a - b);
  const os = sizes(oracle);
  const cs = sizes(candidate);
  let maxSizeDeltaIn = 0;
  for (let i = 0; i < Math.min(os.length, cs.length); i++) {
    maxSizeDeltaIn = Math.max(maxSizeDeltaIn, Math.abs(os[i]! - cs[i]!));
  }

  return {
    nodeCountOk,
    edgeCountOk,
    degreeOk,
    minlenOk,
    structurallyEqual: nodeCountOk && edgeCountOk && degreeOk && minlenOk,
    oracle: {
      nodes: oracle.nodes.length,
      edges: oracle.edges.length,
      degree: od,
      subgraphs: oracle.subgraphCount,
    },
    candidate: { nodes: candidate.nodes.length, edges: candidate.edges.length, degree: cd },
    maxSizeDeltaIn,
    attrs: {
      oracle: [oracle.nodesep, oracle.ranksep],
      candidate: [candidate.nodesep, candidate.ranksep],
    },
  };
}
