/**
 * symbols-box.test.ts — T5: conformance + placement-math tests for the
 * box family (`USymbolRectangle`/`Card`/`Action`/`Label`/`Collections`/
 * `Stack`).
 *
 * Provenance for every real-jar fragment/number below:
 * `plantuml-1.2026.7beta3.jar -tsvg -pipe`, single-entity `.puml`
 * sources (`rectangle Foo` / `agent Foo` / `card Foo` / `action Foo` /
 * `label Foo` — each byte-verified to render at absolute origin
 * `(7,7)`, PlantUML's fixed content padding for a single, unlinked
 * DESCRIPTION-diagram entity) plus a `skinparam rectangleDiagonalCorner
 * 10` variant for the diagonal-corner case. `collections`/`stack` alone
 * (no link) misdetect as a SEQUENCE diagram (verified: jar's diagram-
 * type heuristic, not a port bug) — captured instead as `collections
 * Foo` / `stack Foo` alongside an unlinked `rectangle dummy` (forces
 * DESCRIPTION diagram type without introducing any layout-affecting
 * link), then their geometry re-derived onto the SAME `(7,7)` origin
 * every other case uses (arithmetic re-basing, not fabricated data —
 * every offset/radius/dimension below is read off real jar bytes; only
 * the coordinate origin is normalized so all six cases share one
 * reference frame). `"Foo"`'s real jar text metrics (`sans-serif`/14px):
 * width `24.7051`, height `16.4883` (label dimension = margin-subtracted
 * from jar's real overall box size, consistent across every case
 * below — cross-checked pairwise). Root `viewBox`/`width`/`height` for
 * each case is derived (not captured — no real jar diagram isolates a
 * bare symbol) from `SvgGraphicsCore#ensureVisible`'s documented,
 * already-conformant algorithm (`ensureVisible(x,y)`: `maxX =
 * max(maxX, trunc(x)+1)`, starting at `(10,10)`) applied to each case's
 * own real jar shape coordinates — never generated by running this
 * port's own emitter (verified independently via a throwaway Python
 * transcription of the same formula, not trusted "by construction").
 *
 * Text rendering itself is out of this task's scope (proven elsewhere,
 * Brief 1 T6's `emitter.golden.test.ts` suite) — every label/stereotype
 * `TextBlock` here is a lightweight double reporting the real jar
 * dimension above but drawing nothing (a `getTranslate()` spy instead),
 * so each conformance assertion below covers exactly this task's scope:
 * `SymbolContext` application, shape geometry/`deltaShadow`/corner
 * handling, and stereotype/label placement math (the `UTranslate` the
 * symbol hands the label/stereotype `TextBlock`, captured by the spy).
 */
import { describe, test, expect } from 'vitest';
import { UGraphicSvg } from '../../../../src/core/klimt/drawing/svg/u-graphic-svg.js';
import { basicSvgOption } from '../../../../src/core/klimt/drawing/svg/svg-graphics.js';
import { UStroke } from '../../../../src/core/klimt/UStroke.js';
import { UTranslate } from '../../../../src/core/klimt/UTranslate.js';
import type { UGraphic } from '../../../../src/core/klimt/UGraphic.js';
import type { TextBlock } from '../../../../src/core/klimt/shape/TextBlock.js';
import { XDimension2D } from '../../../../src/core/klimt/geom/XDimension2D.js';
import { HorizontalAlignment } from '../../../../src/core/klimt/geom/HorizontalAlignment.js';
import { SymbolContext } from '../../../../src/core/decoration/symbol/SymbolContext.js';
import { USymbolRectangle } from '../../../../src/core/decoration/symbol/USymbolRectangle.js';
import { USymbolCard } from '../../../../src/core/decoration/symbol/USymbolCard.js';
import { USymbolAction } from '../../../../src/core/decoration/symbol/USymbolAction.js';
import { USymbolLabel } from '../../../../src/core/decoration/symbol/USymbolLabel.js';
import { USymbolCollections } from '../../../../src/core/decoration/symbol/USymbolCollections.js';
import { USymbolStack } from '../../../../src/core/decoration/symbol/USymbolStack.js';
import { compareSvg } from '../../../oracle/svg-conformance/compare.js';

// ---------------------------------------------------------------------------
// Shared test doubles / helpers
// ---------------------------------------------------------------------------

const FOO_WIDTH = 24.7051;
const FOO_HEIGHT = 16.4883;

const EMPTY_STEREOTYPE: TextBlock = {
  calculateDimension: () => new XDimension2D(0, 0),
  drawU: () => {
    // Intentionally empty — represents an absent stereotype (0x0, no-op
    // draw), matching how EntityImageDescription passes an empty
    // TextBlock when no stereotype is present.
  },
};

/** A spy `TextBlock` reporting a fixed `(width, height)` dimension and
 * recording the `UTranslate` it was drawn with, WITHOUT drawing
 * anything visible — text-rendering fidelity is out of this task's
 * scope (see module doc comment). Used for label/title/stereotype
 * doubles alike. */
function spyBlock(width: number, height: number): { tb: TextBlock; translate(): UTranslate | undefined } {
  let captured: UTranslate | undefined;
  return {
    tb: {
      calculateDimension: () => new XDimension2D(width, height),
      drawU: (ug: UGraphic) => {
        captured = ug.getTranslate();
      },
    },
    translate: () => captured,
  };
}

/** `Foo`'s real jar-measured dimension (see the module doc comment for
 * provenance) — the label double every `asSmall` conformance test
 * above uses. */
function spyLabel(): { tb: TextBlock; translate(): UTranslate | undefined } {
  return spyBlock(FOO_WIDTH, FOO_HEIGHT);
}

const STUB_STRING_BOUNDER = { calculateDimension: () => ({ width: 0 }) };

function newRoot(): UGraphicSvg {
  return UGraphicSvg.build(0, basicSvgOption(), '$version$', STUB_STRING_BOUNDER);
}

/** Every real-jar single-entity capture this suite conforms against
 * renders at absolute origin `(7,7)` (PlantUML's fixed content padding
 * for an unlinked DESCRIPTION-diagram entity) — see module doc comment. */
const ORIGIN = new UTranslate(7, 7);

function wrapDocument(rootAttrs: string, body: string): string {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" ${rootAttrs}` +
    ` zoomAndPan="magnify" preserveAspectRatio="none" contentStyleType="text/css">` +
    `<?plantuml $version$?><defs/><g>${body}</g></svg>`
  );
}

/** Default `SymbolContext` every box-family conformance case below uses:
 * `backColor=#F1F1F1`, `foreColor=#181818`, `stroke=0.5pt`, no shadow,
 * `roundCorner=5` (halved to `rx=ry=2.5` at serialization — see
 * `URectangle.ts`'s own doc comment), no diagonal corner. Matches every
 * real jar capture's own `fill`/`style`/`rx`/`ry` attributes exactly. */
function defaultContext(): SymbolContext {
  return new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 0, 5, 0);
}

// ---------------------------------------------------------------------------
// USymbolRectangle
// ---------------------------------------------------------------------------

describe('USymbolRectangle', () => {
  const GOLDEN = wrapDocument(
    'style="width:52px;height:44px;" width="52px" height="44px" viewBox="0 0 52 44"',
    '<rect x="7" y="7" width="44.7051" height="36.4883" fill="#F1F1F1" style="stroke:#181818;stroke-width:0.5;" rx="2.5" ry="2.5"/>',
  );

  test('asSmall (rectangle): conformant vs jar fragment (rectangle Foo)', () => {
    const symbol = new USymbolRectangle('rectangle');
    const label = spyLabel();
    const root = newRoot();
    symbol.asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER).drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('agent maps to USymbolRectangle(SName.agent) — byte-identical to the rectangle variant', () => {
    // Verified against USymbols.java:65 — `AGENT = new
    // USymbolRectangle(SName.agent)` — and against real jar output
    // (`agent Foo` vs `rectangle Foo`): identical <rect>/<text>
    // fragments (see module doc comment / this file's write-up in the
    // task report).
    const agentRoot = newRoot();
    new USymbolRectangle('agent')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(agentRoot.apply(ORIGIN));

    const rectRoot = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(rectRoot.apply(ORIGIN));

    expect(agentRoot.getSvgString()).toBe(rectRoot.getSvgString());
  });

  test('asSmall: roundCorner=5 halves to rx=ry=2.5 (URectangle.rounded semantics)', () => {
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(root.getSvgString()).toContain('rx="2.5"');
    expect(root.getSvgString()).toContain('ry="2.5"');
  });

  test('asSmall: diagonalCorner=10 draws a UPath outline, conformant vs jar fragment (skinparam rectangleDiagonalCorner 10)', () => {
    const GOLDEN_DIAGONAL = wrapDocument(
      'style="width:52px;height:44px;" width="52px" height="44px" viewBox="0 0 52 44"',
      '<path d="M17,7 L41.7051,7 L51.7051,17 L51.7051,33.4883 L41.7051,43.4883 L17,43.4883 L7,33.4883 L7,17 L17,7" ' +
        'style="stroke:#181818;stroke-width:0.5;" fill="#F1F1F1"/>',
    );
    const diagonalContext = new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 0, 0, 10);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, diagonalContext, HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN_DIAGONAL, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: label placement translate matches margin (10,10)', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const translate = label.translate();
    expect(translate?.getDx()).toBe(7 + 10);
    expect(translate?.getDy()).toBe(7 + 10);
  });
});

// ---------------------------------------------------------------------------
// USymbolCard
// ---------------------------------------------------------------------------

describe('USymbolCard', () => {
  const GOLDEN = wrapDocument(
    'style="width:52px;height:30px;" width="52px" height="30px" viewBox="0 0 52 30"',
    '<rect x="7" y="7" width="44.7051" height="22.4883" fill="#F1F1F1" style="stroke:#181818;stroke-width:0.5;" rx="2.5" ry="2.5"/>',
  );

  test('asSmall: conformant vs jar fragment (card Foo) — no divider line (top=0)', () => {
    const root = newRoot();
    new USymbolCard()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: label placement translate matches margin (10,3)', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolCard()
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(label.translate()?.getDx()).toBe(7 + 10);
    expect(label.translate()?.getDy()).toBe(7 + 3);
  });
});

// ---------------------------------------------------------------------------
// USymbolAction
// ---------------------------------------------------------------------------

describe('USymbolAction', () => {
  const GOLDEN = wrapDocument(
    'style="width:62px;height:44px;" width="62px" height="44px" viewBox="0 0 62 44"',
    '<polygon points="7,7,51.7051,7,61.7051,25.2441,51.7051,43.4883,7,43.4883" fill="#F1F1F1" ' +
      'style="stroke:#181818;stroke-width:0.5;stroke-linejoin:miter;stroke-miterlimit:10;"/>',
  );

  test('asSmall: conformant vs jar fragment (action Foo) — 5-point chevron polygon', () => {
    const root = newRoot();
    new USymbolAction('action')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: label placement translate matches margin (10,10)', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolAction('action')
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(label.translate()?.getDx()).toBe(7 + 10);
    expect(label.translate()?.getDy()).toBe(7 + 10);
  });

  test('drawAction ignores shadowing/roundCorner/diagonalCorner (faithful upstream bug, not simplified away)', () => {
    // Real jar output for `action Foo` never shows a filter/shadow or
    // rounded/diagonal corner on the chevron regardless of ambient
    // skinparam — USymbolAction.java's drawAction reads none of these
    // params. A non-zero deltaShadow/roundCorner/diagonalCorner context
    // must still produce the IDENTICAL polygon fragment.
    const noisyContext = new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 3, 8, 4);
    const root = newRoot();
    new USymbolAction('action')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, noisyContext, HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const svg = root.getSvgString();
    expect(svg).toContain('<polygon points="7,7,51.7051,7,61.7051,25.2441,51.7051,43.4883,7,43.4883"');
    expect(svg).not.toContain('filter=');
  });
});

// ---------------------------------------------------------------------------
// USymbolLabel
// ---------------------------------------------------------------------------

describe('USymbolLabel', () => {
  test('asSmall: draws no border/shape at all (empty-context behavior, verified against jar: no <rect> in label Foo)', () => {
    const root = newRoot();
    new USymbolLabel()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const GOLDEN = wrapDocument('style="width:10px;height:10px;" width="10px" height="10px" viewBox="0 0 10 10"', '');
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: label placement translate matches margin (10,10) despite drawing no shape', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolLabel()
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(label.translate()?.getDx()).toBe(7 + 10);
    expect(label.translate()?.getDy()).toBe(7 + 10);
  });
});

// ---------------------------------------------------------------------------
// USymbolCollections
// ---------------------------------------------------------------------------

describe('USymbolCollections', () => {
  const GOLDEN = wrapDocument(
    'style="width:52px;height:44px;" width="52px" height="44px" viewBox="0 0 52 44"',
    '<rect x="11" y="11" width="40.7051" height="32.4883" fill="#F1F1F1" style="stroke:#181818;stroke-width:0.5;" rx="2.5" ry="2.5"/>' +
      '<rect x="7" y="7" width="40.7051" height="32.4883" fill="#F1F1F1" style="stroke:#181818;stroke-width:0.5;" rx="2.5" ry="2.5"/>',
  );

  test('asSmall: conformant vs jar fragment (collections Foo) — back-then-front rect draw order', () => {
    const root = newRoot();
    new USymbolCollections()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: emitted rect sequence is back (offset +4,+4, shadow) then front (origin, no shadow)', () => {
    const shadowContext = new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 3, 5, 0);
    const root = newRoot();
    new USymbolCollections()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, shadowContext, HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const svg = root.getSvgString();
    const backIndex = svg.indexOf('x="11" y="11"');
    const frontIndex = svg.indexOf('x="7" y="7"');
    expect(backIndex).toBeGreaterThan(-1);
    expect(frontIndex).toBeGreaterThan(-1);
    expect(backIndex).toBeLessThan(frontIndex);
    // Only the back rect (drawn first) carries the shadow filter — the
    // filter's <defs> registration precedes both rects in document
    // order, so scope the check to the <g>...</g> body, not the whole
    // document.
    const bodyStart = svg.indexOf('<g>');
    const firstRectClose = svg.indexOf('/>', bodyStart);
    expect(svg.slice(bodyStart, firstRectClose)).toContain('filter=');
    expect(svg.slice(firstRectClose)).not.toContain('filter=');
  });

  test('asSmall: label placement translate is margin minus half the collection delta (8,8)', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolCollections()
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(label.translate()?.getDx()).toBe(7 + 8);
    expect(label.translate()?.getDy()).toBe(7 + 8);
  });
});

// ---------------------------------------------------------------------------
// USymbolStack
// ---------------------------------------------------------------------------

describe('USymbolStack', () => {
  const GOLDEN = wrapDocument(
    'style="width:82px;height:46px;" width="82px" height="46px" viewBox="0 0 82 46"',
    '<rect x="22" y="7" width="44.7051" height="36.4883" fill="#F1F1F1" style="stroke:none;stroke-width:0.5;" rx="2.5" ry="2.5"/>' +
      '<path d="M7,7 L19.5,7 A2.5,2.5 0 0 1 22,9.5 L22,40.9883 A2.5,2.5 0 0 0 24.5,43.4883 L64.2051,43.4883 ' +
      'A2.5,2.5 0 0 0 66.7051,40.9883 L66.7051,9.5 A2.5,2.5 0 0 1 69.2051,7 L81.7051,7" style="stroke:#181818;stroke-width:0.5;" fill="none"/>',
  );

  test('asSmall: conformant vs jar fragment (stack Foo, re-based to origin (7,7))', () => {
    const root = newRoot();
    new USymbolStack()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const { pass, diffs } = compareSvg(root.getSvgString(), GOLDEN, 'deterministic');
    expect(pass, JSON.stringify(diffs[0])).toBe(true);
  });

  test('asSmall: rect (drawn first) has foreColor overridden to none; path (drawn second) has backColor overridden to none', () => {
    const root = newRoot();
    new USymbolStack()
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const svg = root.getSvgString();
    const rectIndex = svg.indexOf('<rect');
    const pathIndex = svg.indexOf('<path');
    expect(rectIndex).toBeGreaterThan(-1);
    expect(pathIndex).toBeGreaterThan(rectIndex);
    expect(svg.slice(rectIndex, pathIndex)).toContain('stroke:none');
    expect(svg.slice(pathIndex)).toContain('fill="none"');
  });

  test('asSmall: label placement translate matches margin (25,10)', () => {
    const label = spyLabel();
    const root = newRoot();
    new USymbolStack()
      .asSmall(EMPTY_STEREOTYPE, label.tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(label.translate()?.getDx()).toBe(7 + 25);
    expect(label.translate()?.getDy()).toBe(7 + 10);
  });
});

// ---------------------------------------------------------------------------
// mergeTB horizontalOffset branches (LEFT/RIGHT) — CENTER is already
// exercised by every asSmall test above.
// ---------------------------------------------------------------------------

describe('mergeTB (shared by every asSmall above)', () => {
  test('stereoAlignment=LEFT: stereotype (0-width) offsets to dx=0', () => {
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.LEFT)
      .drawU(root.apply(ORIGIN));
    // No throw, no diff vs the CENTER case in observable shape output
    // (stereotype is 0-width either way) — this exercises the LEFT
    // branch of horizontalOffset for coverage/regression purposes.
    expect(root.getSvgString()).toContain('<rect');
  });

  test('stereoAlignment=RIGHT: stereotype (0-width) offsets to dx=totalWidth', () => {
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asSmall(EMPTY_STEREOTYPE, spyLabel().tb, EMPTY_STEREOTYPE, defaultContext(), HorizontalAlignment.RIGHT)
      .drawU(root.apply(ORIGIN));
    expect(root.getSvgString()).toContain('<rect');
  });
});

// ---------------------------------------------------------------------------
// asBig — functional/placement coverage (dimension is caller-supplied,
// not jar-fragment conformance; text rendering is out of scope, see
// module doc comment). Exercises every labelAlignment/stereoAlignment
// branch across the family.
// ---------------------------------------------------------------------------

describe('asBig — USymbolRectangle', () => {
  test('calculateDimension returns the caller-supplied (width, height) verbatim', () => {
    const tb = new USymbolRectangle('rectangle').asBig(
      spyBlock(30, 12).tb,
      HorizontalAlignment.CENTER,
      EMPTY_STEREOTYPE,
      100,
      50,
      defaultContext(),
      HorizontalAlignment.CENTER,
    );
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
  });

  test('CENTER/CENTER: stereotype and title both center-aligned', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(stereo.translate()?.getDx()).toBe(7 + (100 - 20) / 2);
    expect(stereo.translate()?.getDy()).toBe(7 + 2);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
    expect(title.translate()?.getDy()).toBe(7 + 2 + 8);
  });

  test('stereoAlignment=RIGHT: stereotype right-aligned with half-margin offset', () => {
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asBig(spyBlock(30, 12).tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.RIGHT)
      .drawU(root.apply(ORIGIN));
    expect(stereo.translate()?.getDx()).toBe(7 + 100 - 20 - 5);
    expect(stereo.translate()?.getDy()).toBe(7 + 5);
  });

  test('labelAlignment=LEFT: title at fixed x=3', () => {
    const title = spyBlock(30, 12);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asBig(title.tb, HorizontalAlignment.LEFT, EMPTY_STEREOTYPE, 100, 50, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(title.translate()?.getDx()).toBe(7 + 3);
  });

  test('labelAlignment=RIGHT: title right-aligned minus 3', () => {
    const title = spyBlock(30, 12);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asBig(title.tb, HorizontalAlignment.RIGHT, EMPTY_STEREOTYPE, 100, 50, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(title.translate()?.getDx()).toBe(7 + 100 - 30 - 3);
  });

  test('diagonalCorner>0: asBig draws a UPath outline, not a URectangle', () => {
    const diagonalContext = new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 0, 0, 10);
    const root = newRoot();
    new USymbolRectangle('rectangle')
      .asBig(spyBlock(30, 12).tb, HorizontalAlignment.CENTER, EMPTY_STEREOTYPE, 100, 50, diagonalContext, HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(root.getSvgString()).toContain('<path');
    expect(root.getSvgString()).not.toContain('<rect');
  });
});

describe('asBig — USymbolCard', () => {
  test('draws a divider line at dimTitle.height + dimStereo.height + 4', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    const tb = new USymbolCard().asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER);
    tb.drawU(root.apply(ORIGIN));
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
    const svg = root.getSvgString();
    // top = 12 + 8 + 4 = 24 -> hline drawn at translate dy = 7 + 24
    expect(svg).toContain('<line');
    expect(stereo.translate()?.getDx()).toBe(7 + (100 - 20) / 2);
    expect(stereo.translate()?.getDy()).toBe(7 + 2);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
    expect(title.translate()?.getDy()).toBe(7 + 2 + 8);
  });
});

describe('asBig — USymbolAction', () => {
  test('title centered at y=2; stereotype offset by 4 + centered, below getHTitle(dimTitle)', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    const tb = new USymbolAction('action').asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER);
    tb.drawU(root.apply(ORIGIN));
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
    expect(title.translate()?.getDy()).toBe(7 + 2);
    // dimTitle.width !== 0 here, so getHTitle returns dimTitle.getHeight() (12).
    expect(stereo.translate()?.getDx()).toBe(7 + 4 + (100 - 20) / 2);
    expect(stereo.translate()?.getDy()).toBe(7 + 2 + 12);
  });

  test('getHTitle: a zero-width title (empty) falls back to 10, not the title height', () => {
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    new USymbolAction('action')
      .asBig(EMPTY_STEREOTYPE, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(stereo.translate()?.getDy()).toBe(7 + 2 + 10);
  });
});

describe('asBig — USymbolLabel', () => {
  test('CENTER/CENTER placement; draws no shape', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    const tb = new USymbolLabel().asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER);
    tb.drawU(root.apply(ORIGIN));
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
    const svg = root.getSvgString();
    expect(svg).not.toContain('<rect');
    expect(svg).not.toContain('<path');
    expect(stereo.translate()?.getDx()).toBe(7 + (100 - 20) / 2);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
  });

  test('stereoAlignment=RIGHT + labelAlignment=RIGHT', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    new USymbolLabel()
      .asBig(title.tb, HorizontalAlignment.RIGHT, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.RIGHT)
      .drawU(root.apply(ORIGIN));
    expect(stereo.translate()?.getDx()).toBe(7 + 100 - 20 - 5);
    expect(title.translate()?.getDx()).toBe(7 + 100 - 30 - 3);
  });

  test('labelAlignment=LEFT', () => {
    const title = spyBlock(30, 12);
    const root = newRoot();
    new USymbolLabel()
      .asBig(title.tb, HorizontalAlignment.LEFT, EMPTY_STEREOTYPE, 100, 50, defaultContext(), HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    expect(title.translate()?.getDx()).toBe(7 + 3);
  });
});

describe('asBig — USymbolCollections', () => {
  test('draws the same 2-rect stack as asSmall, centered title/stereotype', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    const tb = new USymbolCollections().asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER);
    tb.drawU(root.apply(ORIGIN));
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
    const svg = root.getSvgString();
    expect((svg.match(/<rect/g) ?? []).length).toBe(2);
    expect(stereo.translate()?.getDx()).toBe(7 + (100 - 20) / 2);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
  });

  test('stereoAlignment=RIGHT', () => {
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    new USymbolCollections()
      .asBig(spyBlock(30, 12).tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.RIGHT)
      .drawU(root.apply(ORIGIN));
    expect(stereo.translate()?.getDx()).toBe(7 + 100 - 20 - 5);
  });
});

describe('asBig — USymbolStack', () => {
  test('stereotype/title centered below y=13', () => {
    const title = spyBlock(30, 12);
    const stereo = spyBlock(20, 8);
    const root = newRoot();
    const tb = new USymbolStack().asBig(title.tb, HorizontalAlignment.CENTER, stereo.tb, 100, 50, defaultContext(), HorizontalAlignment.CENTER);
    tb.drawU(root.apply(ORIGIN));
    const dim = tb.calculateDimension(STUB_STRING_BOUNDER as never);
    expect(dim.getWidth()).toBe(100);
    expect(dim.getHeight()).toBe(50);
    expect(stereo.translate()?.getDx()).toBe(7 + (100 - 20) / 2);
    expect(stereo.translate()?.getDy()).toBe(7 + 13);
    expect(title.translate()?.getDx()).toBe(7 + (100 - 30) / 2);
    expect(title.translate()?.getDy()).toBe(7 + 13 + 8);
  });

  test('roundCorner=0: outline uses the straight-line (non-arc) branch', () => {
    const squareContext = new SymbolContext('#F1F1F1', '#181818', UStroke.withThickness(0.5), 0, 0, 0);
    const root = newRoot();
    new USymbolStack()
      .asBig(spyBlock(30, 12).tb, HorizontalAlignment.CENTER, EMPTY_STEREOTYPE, 100, 50, squareContext, HorizontalAlignment.CENTER)
      .drawU(root.apply(ORIGIN));
    const svg = root.getSvgString();
    expect(svg).toContain('<path');
    const dMatch = /<path d="([^"]*)"/.exec(svg);
    expect(dMatch?.[1]).not.toMatch(/A/); // no elliptical-arc command in the path 'd' string
  });
});

// ---------------------------------------------------------------------------
// getSNames — the style-selector name each symbol answers to.
// ---------------------------------------------------------------------------

describe('getSNames', () => {
  test('USymbolRectangle reports the constructor-supplied SName', () => {
    expect(new USymbolRectangle('rectangle').getSNames()).toEqual(['rectangle']);
    expect(new USymbolRectangle('agent').getSNames()).toEqual(['agent']);
  });

  test('USymbolCard reports "card"', () => {
    expect(new USymbolCard().getSNames()).toEqual(['card']);
  });

  test('USymbolAction reports the constructor-supplied SName', () => {
    expect(new USymbolAction('action').getSNames()).toEqual(['action']);
  });

  test('USymbolLabel reports "label"', () => {
    expect(new USymbolLabel().getSNames()).toEqual(['label']);
  });

  test('USymbolCollections reports "collections"', () => {
    expect(new USymbolCollections().getSNames()).toEqual(['collections']);
  });

  test('USymbolStack reports "stack"', () => {
    expect(new USymbolStack().getSNames()).toEqual(['stack']);
  });
});
