/** Renders a package's `generated/index.{js,d.ts}` -- re-exports every
 * named binding from every one of its `GeneratedModule`s. */

import type { PackageSpec } from './types.js';

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

function reExportLine(mod: PackageSpec['modules'][number]): string {
  const names = mod.exports.map((exp) => exp.exportName).join(', ');
  return `export { ${names} } from './${mod.fileBaseName}.js';\n`;
}

export function emitIndexJs(spec: PackageSpec): string {
  const lines = spec.modules.map(reExportLine).join('');
  return GENERATED_HEADER + '\n' + lines;
}

export function emitIndexDts(spec: PackageSpec): string {
  const lines = spec.modules.map(reExportLine).join('');
  return GENERATED_HEADER + '\n' + lines;
}
