/**
 * Renders `packages/stdlib-all/generated/index.{js,d.ts}` -- a re-export of
 * every non-GPL `@plantuml-ts/stdlib*` package (`decisions.md` D2: `adaml`
 * is GPL and is never included here).
 */

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

const ALL_DEPENDENCIES: readonly string[] = [
  '@plantuml-ts/stdlib',
  '@plantuml-ts/stdlib-aws',
  '@plantuml-ts/stdlib-tupadr3',
];

function reExportAllLines(): string {
  return ALL_DEPENDENCIES.map((pkg) => `export * from '${pkg}';\n`).join('');
}

export function emitAllIndexJs(): string {
  return GENERATED_HEADER + '\n' + reExportAllLines();
}

export function emitAllIndexDts(): string {
  return GENERATED_HEADER + '\n' + reExportAllLines();
}
