/**
 * Renders one `GeneratedModule` (types.ts) into a `.js` + `.d.ts` pair.
 *
 * Every file's content and every object key goes through `JSON.stringify` --
 * escaping, not transformation. `JSON.stringify` on a JS string produces a
 * double-quoted JS string literal whose parsed value is byte-identical to
 * the input string (`plans/si5b-stdlib/decisions.md`'s VERBATIM constraint,
 * batch-3/overview.md T8). This is what the round-trip sha256 test in
 * `tests/unit/stdlib-packages.test.ts` proves.
 */

import { readBundleFiles } from './read-bundle.js';
import type { AliasBundleExport, ConcreteBundleExport, GeneratedModule } from './types.js';

const GENERATED_HEADER =
  '// AUTO-GENERATED by scripts/build-stdlib-packages.ts -- DO NOT EDIT.\n' +
  '// Regenerate with: npm run build:stdlib\n';

const DTS_IMPORT = `import type { BundleData } from 'plantuml-ts';\n`;

function emitConcreteJs(bundle: ConcreteBundleExport, assetsStdlibDir: string): string {
  const files = readBundleFiles(assetsStdlibDir, bundle.assetFolder);
  const fileLines = Object.keys(files)
    .sort()
    .map((key) => `    ${JSON.stringify(key)}: ${JSON.stringify(files[key])},`)
    .join('\n');

  return (
    `export const ${bundle.exportName} = {\n` +
    `  name: ${JSON.stringify(bundle.bundleName)},\n` +
    `  files: {\n${fileLines}\n  },\n` +
    `};\n`
  );
}

function emitAliasJs(alias: AliasBundleExport): string {
  return (
    `export const ${alias.exportName} = {\n` +
    `  name: ${JSON.stringify(alias.bundleName)},\n` +
    `  aliasOf: ${JSON.stringify(alias.aliasOf)},\n` +
    `  files: {},\n` +
    `};\n`
  );
}

/** Renders one `GeneratedModule`'s `.js` body. */
export function emitModuleJs(mod: GeneratedModule, assetsStdlibDir: string): string {
  const bodies = mod.exports.map((exp) =>
    exp.kind === 'concrete' ? emitConcreteJs(exp, assetsStdlibDir) : emitAliasJs(exp),
  );
  return GENERATED_HEADER + '\n' + bodies.join('\n');
}

/** Renders one `GeneratedModule`'s `.d.ts` body -- a type-only import of
 * `BundleData` plus one `declare const` per export. */
export function emitModuleDts(mod: GeneratedModule): string {
  const decls = mod.exports.map((exp) => `export declare const ${exp.exportName}: BundleData;\n`).join('');
  return GENERATED_HEADER + '\n' + DTS_IMPORT + '\n' + decls;
}
