/**
 * Built-in PlantUML theme definitions.
 * Auto-generated by scripts/compile-themes.py — do not edit by hand.
 * Re-run the script when upstream themes change.
 */

import type { ThemeOverride } from './theme.js';

/** Partial Theme overrides for each built-in PlantUML theme name. */
export const BUILTIN_THEMES: Record<string, ThemeOverride> = {
  'amiga': {
    fontFamily: 'Verdana',
    colors: {
      background: '#0B58A8',
      text: '#FFFFFF',
      border: '#FFFFFF',
      arrow: '#FFFFFF',
      graph: {
        json: {
          background: '#0B58A8',
          border: '#FFFFFF',
          arrowColor: '#FFFFFF',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'aws-orange': {
    colors: {
      background: 'transparent',
      text: '#232F3E',
      border: '#FF9900',
      arrow: '#FF9900',
    },
  },
  'black-knight': {
    colors: {
      background: 'transparent',
      text: '#FFF200',
      border: '#1C1C1C',
      arrow: '#1C1C1C',
    },
  },
  'bluegray': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#007FAF',
      arrow: '#007FAF',
    },
  },
  'blueprint': {
    fontFamily: 'Verdana',
    colors: {
      background: '#003153',
      text: '#D9D3D0',
      border: '#D9D3D0',
      arrow: '#D9D3D0',
      graph: {
        json: {
          background: '#003153',
          border: '#D9D3D0',
          arrowColor: '#D9D3D0',
          keyText: '#D9D3D0',
          stringValue: '#D9D3D0',
          numberValue: '#D9D3D0',
          booleanValue: '#D9D3D0',
          nullValue: '#D9D3D0',
        },
      },
    },
  },
  'carbon-gray': {
    fontFamily: 'IBM Plex Sans',
    colors: {
      background: 'transparent',
      text: '#F4F4F4',
      border: '#4D4D4D',
      arrow: '#4D4D4D',
    },
  },
  'cerulean-outline': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#2FA4E7',
      border: '#2683B9',
      arrow: '#2683B9',
    },
  },
  'cerulean': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#2683B9',
      arrow: '#2683B9',
    },
  },
  'cloudscape-design': {
    colors: {
      background: 'transparent',
      text: '#000716',
      border: '#0972D3',
      arrow: '#0972D3',
    },
  },
  'crt-amber': {
    fontFamily: 'Verdana',
    colors: {
      background: '#282828',
      text: '#FFB000',
      border: '#FFB000',
      arrow: '#FFB000',
      graph: {
        json: {
          background: '#282828',
          border: '#FFB000',
          arrowColor: '#FFB000',
          keyText: '#FFB000',
          stringValue: '#FFB000',
          numberValue: '#FFB000',
          booleanValue: '#FFB000',
          nullValue: '#FFB000',
        },
      },
    },
  },
  'crt-green': {
    fontFamily: 'Verdana',
    colors: {
      background: '#282828',
      text: '#33FF33',
      border: '#33FF33',
      arrow: '#33FF33',
      graph: {
        json: {
          background: '#282828',
          border: '#33FF33',
          arrowColor: '#33FF33',
          keyText: '#33FF33',
          stringValue: '#33FF33',
          numberValue: '#33FF33',
          booleanValue: '#33FF33',
          nullValue: '#33FF33',
        },
      },
    },
  },
  'cyborg-outline': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#2A9FD6',
      border: '#55B2DE',
      arrow: '#55B2DE',
    },
  },
  'cyborg': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#55B2DE',
      arrow: '#55B2DE',
    },
  },
  'hacker': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#151515',
      border: '#6D8B32',
      arrow: '#6D8B32',
    },
  },
  'lightgray': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#336699',
      border: '#888888',
      arrow: '#888888',
    },
  },
  'mars': {
    colors: {
      background: '#F9F9F9',
      text: '#191919',
      border: '#191919',
      arrow: '#191919',
      graph: {
        json: {
          background: '#F9F9F9',
          border: '#191919',
          arrowColor: '#191919',
          keyText: '#191919',
          stringValue: '#191919',
          numberValue: '#191919',
          booleanValue: '#191919',
          nullValue: '#191919',
        },
      },
    },
  },
  'materia-outline': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#2196F3',
      border: '#1A78C2',
      arrow: '#1A78C2',
    },
  },
  'materia': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#1A78C2',
      arrow: '#1A78C2',
    },
  },
  'metal': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#4682B4',
      border: '#B7B6B5',
      arrow: '#B7B6B5',
    },
  },
  'mimeograph': {
    fontFamily: 'Verdana',
    colors: {
      background: '#D9D3D0',
      text: '#9275B6',
      border: '#9275B6',
      arrow: '#9275B6',
      graph: {
        json: {
          background: '#D9D3D0',
          border: '#9275B6',
          arrowColor: '#9275B6',
          keyText: '#9275B6',
          stringValue: '#9275B6',
          numberValue: '#9275B6',
          booleanValue: '#9275B6',
          nullValue: '#9275B6',
        },
      },
    },
  },
  'minty': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#6CAF9C',
      arrow: '#6CAF9C',
    },
  },
  'mono': {
    fontFamily: 'Hack',
    colors: {
      background: 'white',
      text: 'black',
      border: 'black',
      arrow: 'black',
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
        },
      },
    },
  },
  'plain': {
    fontFamily: 'Verdana',
    colors: {
      background: 'white',
      text: 'black',
      border: 'black',
      arrow: 'black',
      graph: {
        json: {
          background: 'white',
          border: 'black',
          arrowColor: 'black',
          keyText: 'black',
          stringValue: 'black',
          numberValue: 'black',
          booleanValue: 'black',
          nullValue: 'black',
        },
      },
    },
  },
  'reddress-darkblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-darkred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#2E2E2E',
      text: '#FFFFFF',
      border: '#1B1B1B',
      arrow: '#1B1B1B',
      graph: {
        json: {
          background: '#2E2E2E',
          border: '#1B1B1B',
          arrowColor: '#1B1B1B',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'reddress-lightblue': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightgreen': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightorange': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'reddress-lightred': {
    fontFamily: 'Verdana',
    colors: {
      background: '#EEEEEE',
      text: '#222222',
      border: '#888888',
      arrow: '#888888',
      graph: {
        json: {
          background: '#EEEEEE',
          border: '#888888',
          arrowColor: '#888888',
          keyText: '#222222',
          stringValue: '#222222',
          numberValue: '#222222',
          booleanValue: '#222222',
          nullValue: '#222222',
        },
      },
    },
  },
  'sandstone': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#2D547A',
      arrow: '#2D547A',
    },
  },
  'silver': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#336699',
      border: '#BEBEBE',
      arrow: '#BEBEBE',
    },
  },
  'sketchy-outline': {
    fontFamily: 'Segoe Print',
    colors: {
      background: 'transparent',
      text: '#2E2E2E',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
    },
  },
  'sketchy': {
    fontFamily: 'Segoe Print',
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#2E2E2E',
      arrow: '#2E2E2E',
    },
  },
  'spacelab-white': {
    fontFamily: 'Verdana',
    colors: {
      background: 'white',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
      graph: {
        json: {
          background: 'white',
          border: '#304D6D',
          arrowColor: '#304D6D',
          keyText: '#FFFFFF',
          stringValue: '#FFFFFF',
          numberValue: '#FFFFFF',
          booleanValue: '#FFFFFF',
          nullValue: '#FFFFFF',
        },
      },
    },
  },
  'spacelab': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFFFFF',
      border: '#304D6D',
      arrow: '#304D6D',
    },
  },
  'sunlust': {
    fontFamily: 'Dejavu Serif',
    colors: {
      background: '#FDF6E3',
      text: '#657B83',
      border: '#657B83',
      arrow: '#657B83',
      graph: {
        json: {
          background: '#FDF6E3',
          border: '#657B83',
          arrowColor: '#657B83',
          keyText: '#657B83',
          stringValue: '#657B83',
          numberValue: '#657B83',
          booleanValue: '#657B83',
          nullValue: '#657B83',
        },
      },
    },
  },
  'superhero-outline': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#DF691A',
      border: '#E58748',
      arrow: '#E58748',
    },
  },
  'superhero': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#FFF',
      border: '#E58748',
      arrow: '#E58748',
    },
  },
  'toy': {
    colors: {
      background: '#DDDDDD',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#DDDDDD',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
  'united': {
    fontFamily: 'Verdana',
    colors: {
      background: 'transparent',
      text: '#fff',
      border: '#D24C1D',
      arrow: '#D24C1D',
    },
  },
  'vibrant': {
    colors: {
      background: '#FFFFFF',
      text: '#333333',
      border: '#333333',
      arrow: '#333333',
      graph: {
        json: {
          background: '#FFFFFF',
          border: '#333333',
          arrowColor: '#333333',
          keyText: '#333333',
          stringValue: '#333333',
          numberValue: '#333333',
          booleanValue: '#333333',
          nullValue: '#333333',
        },
      },
    },
  },
};
