#!/usr/bin/env node
/**
 * Oracle gap report.
 *
 * Walks the committed oracle goldens, renders each fixture through plantuml-ts
 * (capturing the graph it feeds graphviz), and compares its structure against
 * the oracle's svek-*.dot. Writes a human-readable map of the target and our
 * distance from it to oracle/GAP.md.
 *
 * The point is NOT to pass — plantuml-ts is not yet faithful to PlantUML. The
 * report is how we see what "faithful" requires.
 *
 * Usage:  npx tsx scripts/oracle-gap.ts
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { renderSync } from '../src/index.js';
import { FormulaMeasurer } from '../src/core/measurer.js';
import { setLayoutInputObserver } from '../src/core/graph-layout.js';
import type { DotInputGraph } from '../src/core/graph-layout.js';
import {
  parseSvekDot,
  dotInputToStructural,
  compareStructural,
  type StructuralDiff,
} from '../tests/oracle/svek-dot.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const GOLDENS = join(REPO, 'oracle', 'goldens');

interface Row {
  type: string;
  slug: string;
  svekCount: number;
  capCount: number;
  diffs: StructuralDiff[];
}

function svekFiles(dir: string): string[] {
  return readdirSync(dir)
    .filter((f) => /^svek-\d+\.dot$/.test(f))
    .sort((a, b) => Number(a.match(/\d+/)![0]) - Number(b.match(/\d+/)![0]))
    .map((f) => join(dir, f));
}

function captureInputs(puml: string): DotInputGraph[] {
  const inputs: DotInputGraph[] = [];
  setLayoutInputObserver((g) => inputs.push(g));
  try {
    renderSync(puml, { measurer: new FormulaMeasurer() });
  } finally {
    setLayoutInputObserver(undefined);
  }
  return inputs;
}

function rowFor(type: string, slug: string, dir: string): Row {
  const svek = svekFiles(dir);
  const inputs = captureInputs(readFileSync(join(dir, 'input.puml'), 'utf8'));
  const n = Math.min(svek.length, inputs.length);
  const diffs: StructuralDiff[] = [];
  for (let i = 0; i < n; i++) {
    diffs.push(
      compareStructural(
        parseSvekDot(readFileSync(svek[i]!, 'utf8')),
        dotInputToStructural(inputs[i]!),
      ),
    );
  }
  return { type, slug, svekCount: svek.length, capCount: inputs.length, diffs };
}

function discover(): Row[] {
  if (!existsSync(GOLDENS)) return [];
  const rows: Row[] = [];
  for (const type of readdirSync(GOLDENS).sort()) {
    const typeDir = join(GOLDENS, type);
    for (const slug of readdirSync(typeDir).sort()) {
      const dir = join(typeDir, slug);
      if (existsSync(join(dir, 'input.puml')) && svekFiles(dir).length > 0) {
        rows.push(rowFor(type, slug, dir));
      }
    }
  }
  return rows;
}

function verdict(row: Row): string {
  if (row.svekCount !== row.capCount) {
    return `⚠️ graph count: oracle ${row.svekCount} vs ours ${row.capCount}`;
  }
  const fails = row.diffs.filter((d) => !d.structurallyEqual);
  if (fails.length === 0) return '✅ structural match';
  const reasons = new Set<string>();
  for (const d of fails) {
    if (!d.nodeCountOk) reasons.add(`nodes ${d.oracle.nodes}≠${d.candidate.nodes}`);
    if (!d.edgeCountOk) reasons.add(`edges ${d.oracle.edges}≠${d.candidate.edges}`);
    if (!d.degreeOk) {
      reasons.add(`degree [${d.oracle.degree}]≠[${d.candidate.degree}]`);
    }
    if (!d.minlenOk) reasons.add('minlen differs');
  }
  return `❌ ${[...reasons].join('; ')}`;
}

function metricNote(row: Row): string {
  const maxDelta = Math.max(0, ...row.diffs.map((d) => d.maxSizeDeltaIn));
  return `${maxDelta.toFixed(2)}″`;
}

function renderReport(rows: Row[]): string {
  const lines: string[] = [
    '# Oracle gap report',
    '',
    'Generated by `npx tsx scripts/oracle-gap.ts`. The oracle is the target —',
    'this maps how plantuml-ts currently diverges from PlantUML\'s own DOT, not a',
    'pass/fail bar. Structural facts (node/edge counts, topology, minlen) must',
    'eventually match; node sizes are tolerant metrics (max Δ shown, in inches).',
    '',
  ];
  const byType = new Map<string, Row[]>();
  for (const r of rows) byType.set(r.type, [...(byType.get(r.type) ?? []), r]);

  for (const [type, typeRows] of byType) {
    const matched = typeRows.filter((r) => verdict(r).startsWith('✅')).length;
    lines.push(`## ${type} — ${matched}/${typeRows.length} structurally match`, '');
    lines.push('| fixture | oracle n/e | ours n/e | verdict | max size Δ |');
    lines.push('|---|---|---|---|---|');
    for (const r of typeRows) {
      const o = r.diffs[0]?.oracle;
      const c = r.diffs[0]?.candidate;
      const oCol = o ? `${o.nodes}/${o.edges}` : '—';
      const cCol = c ? `${c.nodes}/${c.edges}` : '—';
      lines.push(`| ${r.slug} | ${oCol} | ${cCol} | ${verdict(r)} | ${metricNote(r)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

const rows = discover();
const report = renderReport(rows);
writeFileSync(join(REPO, 'oracle', 'GAP.md'), report);
const matched = rows.filter((r) => verdict(r).startsWith('✅')).length;
// eslint-disable-next-line no-console
console.log(`oracle/GAP.md written — ${matched}/${rows.length} fixtures structurally match`);
