/**
 * description-doc-dims.test.ts — G0/T3 (LimitFinder mission) acceptance
 * pin: the F4 "document dimensions 1px short" defect (327/348 diverging
 * description fixtures, mission research) is fixed by cutting the
 * description engine's document sizing over to the `SvekResult` recipe
 * (`renderer-ink-extent.ts#computeDocumentDims`) — see that module's own
 * doc comment for the full upstream chain (`SvekResult#calculateDimension`
 * + the `CucaDiagram` outer margin).
 *
 * Pins the three named F4 fixtures — `vapalu-27-muxa300`,
 * `jesibe-85-sozu187`, `cifaki-66-boxa005` (the last of which is ALSO the
 * mission's own "190×65 fixture" — `cifaki`'s jar-cached document is
 * exactly 190×65, see README.md's exit bar) — against their jar-captured
 * `test-results/dot-cache/component/<slug>/in.svg` `width`/`height`
 * attributes. Renders via `renderFixture` (`tests/oracle/svg-conformance/
 * render-fixture.ts`, the same low-level pipeline + `DeterministicMeasurer`
 * the SVG-conformance ratchet uses) since the jar-cached fixtures were
 * captured under `-DPLANTUML_DETERMINISTIC_TEXT=true`
 * (`scripts/dot-sync-report.ts:133,173`) — comparing against
 * production's `jarMeasurer` would conflate this task's dims fix with the
 * unrelated D12 text-measurer gap (see `tests/integration/description.
 * test.ts`'s own `ALLOWED_DIFF_ATTRS` doc comment for that distinction).
 *
 * `test-results/dot-cache/**` is gitignored and regenerated by
 * `scripts/dot-sync-report.ts` / `scripts/capture-corpus.ts` — this test
 * skips gracefully (not a failure) if the cache is absent, matching the
 * project's other dot-cache-dependent test conventions.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { DeterministicMeasurer } from '../../src/core/measurer-deterministic.js';
import { renderFixture } from '../oracle/svg-conformance/render-fixture.js';

interface F4Fixture {
  readonly slug: string;
  readonly type: 'component' | 'usecase';
  readonly note?: string;
}

// The three named F4 fixtures (mission task spec, T3-description-dims-
// cutover.md). `cifaki-66-boxa005` is independently the mission's "190×65
// fixture" acceptance criterion — its jar-cached document IS 190×65, so
// one slug satisfies both requirements (verified via
// `test-results/dot-cache/component/cifaki-66-boxa005/in.svg`).
const F4_FIXTURES: readonly F4Fixture[] = [
  { slug: 'vapalu-27-muxa300', type: 'component' },
  { slug: 'jesibe-85-sozu187', type: 'component' },
  { slug: 'cifaki-66-boxa005', type: 'component', note: 'also the mission’s 190×65 fixture' },
];

function fixtureDir(f: F4Fixture): string {
  return join(process.cwd(), 'test-results', 'dot-cache', f.type, f.slug);
}

function readJarDims(f: F4Fixture): { width: string; height: string } {
  const svg = readFileSync(join(fixtureDir(f), 'in.svg'), 'utf8');
  const widthMatch = /\swidth="(\d+)px"/.exec(svg);
  const heightMatch = /\sheight="(\d+)px"/.exec(svg);
  if (widthMatch === null || heightMatch === null) {
    throw new Error(`${f.slug}: jar-cached in.svg has no width/height attribute`);
  }
  return { width: widthMatch[1]!, height: heightMatch[1]! };
}

function readOurDims(svg: string): { width: string; height: string } {
  const widthMatch = /\swidth="(\d+)px"/.exec(svg);
  const heightMatch = /\sheight="(\d+)px"/.exec(svg);
  if (widthMatch === null || heightMatch === null) {
    throw new Error('our rendered svg has no width/height attribute');
  }
  return { width: widthMatch[1]!, height: heightMatch[1]! };
}

const availableFixtures = F4_FIXTURES.filter((f) => existsSync(fixtureDir(f)));

describe.skipIf(availableFixtures.length === 0)(
  'description document dims — F4 defect fix (G0/T3)',
  () => {
    for (const f of availableFixtures) {
      const label = f.note !== undefined ? `${f.slug} (${f.note})` : f.slug;

      it(`${label}: our emitted document width/height EQUAL the jar's cached in.svg exactly`, () => {
        const markup = readFileSync(join(fixtureDir(f), 'in.puml'), 'utf8');
        const jarDims = readJarDims(f);

        const ours = renderFixture(markup, new DeterministicMeasurer());
        const ourDims = readOurDims(ours);

        expect(ourDims.width, `${f.slug}: width mismatch`).toBe(jarDims.width);
        expect(ourDims.height, `${f.slug}: height mismatch`).toBe(jarDims.height);
      });
    }

    it('cifaki-66-boxa005 is exactly the mission’s 190×65 exit-bar fixture', () => {
      const cifaki = F4_FIXTURES.find((f) => f.slug === 'cifaki-66-boxa005')!;
      if (!existsSync(fixtureDir(cifaki))) return;
      const jarDims = readJarDims(cifaki);
      expect(jarDims).toEqual({ width: '190', height: '65' });
    });
  },
);

if (availableFixtures.length === 0) {
  it('dot-cache is not populated locally — skipped gracefully (not a failure)', () => {
    expect(availableFixtures).toHaveLength(0);
  });
}
