/**
 * database-cylinder-dashed — T6 golden case: cubic-bezier `UPath`
 * rendering (a "database" stereotype's cylinder body + cap-line) and
 * dashed stroke (`UStroke` dash/space, `SvgGraphics#styleMe`'s
 * `stroke-dasharray`).
 *
 * Provenance: `golden.svg` is a WRAPPED FRAGMENT — the two `<path>`
 * elements are copied verbatim from the cached real jar fixture
 * `test-results/dot-cache/component/bisedo-29-kone620/in.svg` (the
 * "database" element's cylinder body + top cap-line; that fixture's own
 * `<svg>` is a much larger multi-element diagram, out of this case's
 * scope per the mission brief's "wrap fragments in a minimal jar-shaped
 * document" allowance). The wrapper's root attrs (`viewBox`/`width`/
 * `height`/`style`) are NOT copied from that larger diagram — they are
 * hand-derived from `SvgGraphicsCore`'s own documented, byte-verified
 * algorithm (`ensureVisible`/`format`/`finalizeRootAttributes`, already
 * proven correct against 3 other real-jar goldens in this suite):
 * starting `maxX=maxY=10`, each segment's `ensureVisible` call over
 * these exact two paths' real coordinates converges to `maxX=454`,
 * `maxY=105` (no `deltaShadow`, `minDim` left at the `{0,0}` default,
 * `backcolor` left `undefined` so no extra background rect/style is
 * emitted) — never generated by running this port's own emitter.
 */
import { UGraphicSvg } from '../../../../src/core/klimt/drawing/svg/u-graphic-svg.js';
import { basicSvgOption } from '../../../../src/core/klimt/drawing/svg/svg-graphics.js';
import { UPath } from '../../../../src/core/klimt/shape/UPath.js';
import { UStroke } from '../../../../src/core/klimt/UStroke.js';
import { Fore } from '../../../../src/core/klimt/Fore.js';
import { Back } from '../../../../src/core/klimt/Back.js';

const DASH_STROKE = new UStroke(1, 3, 1);

function cylinderBody(): UPath {
  const path = UPath.none();
  path.moveTo(380, 16);
  path.cubicTo(380, 6, 416.5, 6, 416.5, 6);
  path.cubicTo(416.5, 6, 453, 6, 453, 16);
  path.lineTo(453, 94);
  path.cubicTo(453, 104, 416.5, 104, 416.5, 104);
  path.cubicTo(416.5, 104, 380, 104, 380, 94);
  path.lineTo(380, 16);
  return path;
}

function cylinderCap(): UPath {
  const path = UPath.none();
  path.moveTo(380, 16);
  path.cubicTo(380, 26, 416.5, 26, 416.5, 26);
  path.cubicTo(416.5, 26, 453, 26, 453, 16);
  return path;
}

export function render(): string {
  const root = UGraphicSvg.build(0, basicSvgOption(), '$version$', {
    calculateDimension: () => ({ width: 0 }),
  });

  root.apply(new Fore('#0000FF')).apply(new Back('#F0F8FF')).apply(DASH_STROKE).draw(cylinderBody());
  root.apply(new Fore('#0000FF')).apply(DASH_STROKE).draw(cylinderCap());

  return root.getSvgString();
}
